# Bag of Words

En este notebook vamos a ver un ejemplo práctico de la técnica de "Bag of Words".

Como hemos visto, cuando operamos con textos, no hay ninguna operación matemática definida que pueda trabajar con ellos directamente. Por ejemplo, no podemos combinar las palabras _"hola"_ y _"adiós"_. 

Por lo tanto, para poder utilizar textos definidos en lenguaje natural, independientemente del idioma utilizado, necesitamos **transformar estos textos en vectores numéricos** que los representen.

La técnica más conocida para hacer esta transformación se llama ***bolsa de palabras*** o **Bag of Words**. 

Veamos cómo funciona con un ejemplo. Supongamos que tenemos el siguiente texto

> *El miedo es el camino hacia el Lado Oscuro. El miedo lleva a la ira, la ira lleva al odio, el odio lleva al sufrimiento. Percibo mucho miedo en ti.* — Yoda a Anakin en el Consejo Jedi.

El primer paso que debemos realizar es la limpieza del dataset de caracteres extraños y homogeneizarlo a minúsculas:

> el miedo es el camino hacia el lado oscuro el miedo lleva a la ira la ira lleva al odio el odio lleva al sufrimiento percibo mucho miedo en ti

Después, procederemos con la **tokenización**, que consiste en transformar el texto anterior en una matriz de palabras. 

Es decir, vamos a separar cada una de las palabras que componen la frase anterior utilizando espacios separadores. Por tanto, obtendríamos la siguiente lista de *tokens*:

`['el', 'miedo', 'es', 'el', 'camino, 'hacia', 'el', 'lado', 'oscuro', 'el', 'miedo', 'lleva', 'a', 'la', 'ira', 'la', 'ira', 'lleva', 'al', 'odio', 'el', 'odio', 'lleva', 'al', 'sufrimiento', 'percibo', 'mucho', 'miedo', 'en', 'ti']`.

A partir de la lista anterior podemos construir un **diccionario** que contenga todas las palabras definidas en nuestro vocabulario. 

Entendemos por "nuestro vocabulario" las palabras que aparecen en los textos que estamos analizando. Así, analizando los *tokens* anteriores construiremos el siguiente diccionario:

`['el', 'miedo', 'es', 'camino, 'hacia', 'lado', 'oscuro', 'lleva', 'a', 'la', 'ira', 'al', 'odio', 'sufrimiento', 'percibo', 'mucho', 'en', 'ti']`

Por último, tenemos que transformar el texto original en un vector numérico de forma que las posiciones del vector representen las posiciones de las palabras del diccionario y los valores del vector representen el número de apariciones de la palabra del diccionario en el texto analizado. 

Dado que nuestro diccionario consta de 18 palabras, nuestro texto quedaría definido por el siguiente vector

`[5, 3, 1, 1, 1, 1, 1, 3, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1]`

Viéndolo en formato tabla es más fácil de detectar:

| | el | miedo | es | camino | hacia | lado | oscuro | lleva | a | la | ira | al | odio | sufrimiento | percibo | mucho | en | ti |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Frecuencia | 5 | 3 | 1 | 1 | 1 | 1 | 1 | 3 | 1 | 2 | 2 | 2 | 2 | 1 | 1 | 1 | 1 | 1 |

Analizándolo vemos que la palabra *'miedo'* se repite 3 veces, la palabra *'ira'* 2, la palabra *'el'* 5, y así sucesivamente.

En este caso hemos dejado la limpieza de las stop-words para después, pues nos interesaba ver el cambio entre el antes y el después.

Si eliminaramos las stop-words veríamos que desparecen los artículos, determinantes, preposiciones, etc.

En lugar de hacerlo manualmente, como hasta ahora, vamos a hacerlo con Python.

La forma más rápida de hacerlo es utilizando el objeto `CountVectorizer` del paquete `feature_extraction.text` de la librería `scikit-learn`.


In [1]:
import sklearn
import numpy as np

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()

In [4]:
corpus = [
    "El miedo es el camino hacia el Lado Oscuro. El miedo lleva a la ira, la ira lleva al odio, el odio lleva al sufrimiento. Percibo mucho miedo en ti."
]

X = count_vectorizer.fit_transform(corpus) # Fit the Data: vector with the amount of times a word appears in the corpus

print(X.toarray())


[[2 1 5 1 1 1 2 2 1 3 3 1 2 1 1 1 1]]


Podemos ver el mapeo mediante la función `get_feature_names_out()`. Como podéis observar, ésta función detecta los símbolos de puntuación y los ignora.

In [5]:
print(count_vectorizer.get_feature_names_out()) # Get feature names whihle ignoring accents

['al' 'camino' 'el' 'en' 'es' 'hacia' 'ira' 'la' 'lado' 'lleva' 'miedo'
 'mucho' 'odio' 'oscuro' 'percibo' 'sufrimiento' 'ti']


Veamos ahora si elimináramos las stop-words:

In [6]:
#!sudo pip install -U nltk
# %pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [7]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\franz\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

En este caso, es necesario limpiar el dataset y homogeneizar a minusculas antes de usar `nltk`:

In [8]:
import re
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [9]:
# añadimos algunos más que no están en string.punctuation, como las comillas y 
# las aperturas de interrogación/exclamación
# si no los añadiésemos, no se eliminarían
chars = string.punctuation + '“”¡¿'
print(chars)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~“”¡¿


In [10]:
re_punc = re.compile('[%s]' % re.escape(chars))
# eliminar la puntuación de cada palabra
texto = re_punc.sub('', corpus[0])
print(texto)

El miedo es el camino hacia el Lado Oscuro El miedo lleva a la ira la ira lleva al odio el odio lleva al sufrimiento Percibo mucho miedo en ti


Convertimos el texto a minúsculas:

In [11]:
texto = texto.lower()
print(texto)

el miedo es el camino hacia el lado oscuro el miedo lleva a la ira la ira lleva al odio el odio lleva al sufrimiento percibo mucho miedo en ti


In [12]:
stop_words = stopwords.words('spanish')
palabras = texto.split(' ')
print(palabras)

['el', 'miedo', 'es', 'el', 'camino', 'hacia', 'el', 'lado', 'oscuro', 'el', 'miedo', 'lleva', 'a', 'la', 'ira', 'la', 'ira', 'lleva', 'al', 'odio', 'el', 'odio', 'lleva', 'al', 'sufrimiento', 'percibo', 'mucho', 'miedo', 'en', 'ti']


Eliminamos las stop-words:

In [13]:
palabras_limpias = [p for p in palabras if p not in stop_words]
print(palabras_limpias)

['miedo', 'camino', 'hacia', 'lado', 'oscuro', 'miedo', 'lleva', 'ira', 'ira', 'lleva', 'odio', 'odio', 'lleva', 'sufrimiento', 'percibo', 'miedo']


Unimos el texto de nuevo:

In [14]:
texto_limpio = ' '.join(palabras_limpias)
print(texto_limpio)

miedo camino hacia lado oscuro miedo lleva ira ira lleva odio odio lleva sufrimiento percibo miedo


Y aplicamos la técnica de Bag of Words:

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()

# el objeto count_vectorizer necesita una lista de textos para funcionar
X = count_vectorizer.fit_transform([texto_limpio])
print(X.toarray())

[[1 1 2 1 3 3 2 1 1 1]]


In [16]:
print(count_vectorizer.get_feature_names_out())

['camino' 'hacia' 'ira' 'lado' 'lleva' 'miedo' 'odio' 'oscuro' 'percibo'
 'sufrimiento']


Comparadlo con la versión sin limpiar:

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()

# el objeto count_vectorizer necesita una lista de textos para funcionar
X = count_vectorizer.fit_transform(corpus)
print(X.toarray())

[[2 1 5 1 1 1 2 2 1 3 3 1 2 1 1 1 1]]


In [18]:
print(count_vectorizer.get_feature_names_out())

['al' 'camino' 'el' 'en' 'es' 'hacia' 'ira' 'la' 'lado' 'lleva' 'miedo'
 'mucho' 'odio' 'oscuro' 'percibo' 'sufrimiento' 'ti']


### Ejercicio 1

Realiza la limpieza del dataset, la eliminación de stop-words y la vectorización del texto (bag of words) del siguiente texto:

> "¿Qué es el honor, comparado con el amor de una mujer? ¿Qué es el deber, comparado con el calor de un hijo recién nacido entre los brazos, o el recuerdo de la sonrisa de un hermano? Aire y palabras. Aire y palabras. Solo somos humanos, y los dioses nos hicieron para el amor. Es nuestra mayor gloria y nuestra peor tragedia." - Maestre Aemon, Juego de Tronos

In [19]:
corpus = ['¿Qué es el honor, comparado con el amor de una mujer? ¿Qué es el deber, comparado con el calor de un hijo recién nacido entre los brazos, o el recuerdo de la sonrisa de un hermano? Aire y palabras. Aire y palabras. Solo somos humanos, y los dioses nos hicieron para el amor. Es nuestra mayor gloria y nuestra peor tragedia.']

In [25]:
# 1. Limpieza ddel texto: puntación, minúscula y accentos, stopwords
import unicodedata

chars = string.punctuation + '“”¡¿'
re_pun = re.compile('[%s]' % re.escape(chars)) 
texto_sin_puntuacion = re_pun.sub('', corpus[0]) 
print(texto_sin_puntuacion)

texto_minuscula = texto_sin_puntuacion.lower() 
print(texto_minuscula)

texto_sin_acentos = unicodedata.normalize('NFD', texto_minuscula).encode('ascii', 'ignore').decode("utf-8")
print(texto_sin_acentos)

palabras = texto_sin_acentos.split(' ')
palabras_limpias = [p for p in palabras if p not in stop_words]
print(palabras_limpias)


Qué es el honor comparado con el amor de una mujer Qué es el deber comparado con el calor de un hijo recién nacido entre los brazos o el recuerdo de la sonrisa de un hermano Aire y palabras Aire y palabras Solo somos humanos y los dioses nos hicieron para el amor Es nuestra mayor gloria y nuestra peor tragedia
qué es el honor comparado con el amor de una mujer qué es el deber comparado con el calor de un hijo recién nacido entre los brazos o el recuerdo de la sonrisa de un hermano aire y palabras aire y palabras solo somos humanos y los dioses nos hicieron para el amor es nuestra mayor gloria y nuestra peor tragedia
que es el honor comparado con el amor de una mujer que es el deber comparado con el calor de un hijo recien nacido entre los brazos o el recuerdo de la sonrisa de un hermano aire y palabras aire y palabras solo somos humanos y los dioses nos hicieron para el amor es nuestra mayor gloria y nuestra peor tragedia
['honor', 'comparado', 'amor', 'mujer', 'deber', 'comparado', 'c

In [26]:
# 2. Tokenización
## ya separado en palabras para la limpieza de stopwords
print(palabras_limpias)

['honor', 'comparado', 'amor', 'mujer', 'deber', 'comparado', 'calor', 'hijo', 'recien', 'nacido', 'brazos', 'recuerdo', 'sonrisa', 'hermano', 'aire', 'palabras', 'aire', 'palabras', 'solo', 'humanos', 'dioses', 'hicieron', 'amor', 'mayor', 'gloria', 'peor', 'tragedia']


In [29]:
# 3. construir el vocabulario (todas las palabras únicas del texto) y crear el matrix (en este caso con sola 1 fila)
texto_limpio = ' '.join(palabras_limpias)
X = count_vectorizer.fit_transform([texto_limpio])
print(X.toarray())
print(count_vectorizer.get_feature_names_out())

[[2 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1]]
['aire' 'amor' 'brazos' 'calor' 'comparado' 'deber' 'dioses' 'gloria'
 'hermano' 'hicieron' 'hijo' 'honor' 'humanos' 'mayor' 'mujer' 'nacido'
 'palabras' 'peor' 'recien' 'recuerdo' 'solo' 'sonrisa' 'tragedia']


In [39]:
# 4. codificar el texto en función del vocabulario
import pandas as pd
df = pd.DataFrame(X, columns=count_vectorizer.get_feature_names_out())
df

aire  amor  brazos  calor  comparado  deber  dioses  gloria  hermano  \
0   1.0   2.0     2.0    1.0        1.0    1.0     1.0     1.0      1.0   

   hicieron  ...  mayor  mujer  nacido  palabras  peor  recien  recuerdo  \
0       1.0  ...    2.0    2.0     1.0       1.0   1.0     1.0       1.0   

   solo  sonrisa  tragedia  
0   1.0      1.0       1.0  

[1 rows x 23 columns]

In [31]:
# alternative en bucle: 3. construir el vocabulario
vocab = {}
for p in palabras_limpias:
    if not p in vocab:
        vocab[p] = 1
    else:
        vocab[p] += 1
print(vocab)

{'honor': 1, 'comparado': 2, 'amor': 2, 'mujer': 1, 'deber': 1, 'calor': 1, 'hijo': 1, 'recien': 1, 'nacido': 1, 'brazos': 1, 'recuerdo': 1, 'sonrisa': 1, 'hermano': 1, 'aire': 2, 'palabras': 2, 'solo': 1, 'humanos': 1, 'dioses': 1, 'hicieron': 1, 'mayor': 1, 'gloria': 1, 'peor': 1, 'tragedia': 1}


In [42]:
# 4. codificar el texto en función del vocabulario - matrix de frecuencias
df = pd.DataFrame([vocab]).reindex(sorted(df.columns), axis=1)
df

aire  amor  brazos  calor  comparado  deber  dioses  gloria  hermano  \
0     2     2       1      1          2      1       1       1        1   

   hicieron  ...  mayor  mujer  nacido  palabras  peor  recien  recuerdo  \
0         1  ...      1      1       1         2     1       1         1   

   solo  sonrisa  tragedia  
0     1        1         1  

[1 rows x 23 columns]

### Ejercicio 2

Realiza la limpieza del dataset, la eliminación de stop-words y la vectorización del texto (bag of words) del siguiente *corpus* de documentos:

> "Cuando se juega al Juego de Tronos, solo se puede ganar o morir." - Cersei Lannister

> "Por qué será que en cuanto un hombre construye un muro, su vecino inmediatamente quiere saber qué hay del otro lado." - Tyrion Lannister

> "¿Qué es el honor, comparado con el amor de una mujer? ¿Qué es el deber, comparado con el calor de un hijo recién nacido entre los brazos, o el recuerdo de la sonrisa de un hermano? Aire y palabras. Aire y palabras. Solo somos humanos, y los dioses nos hicieron para el amor. Es nuestra mayor gloria y nuestra peor tragedia." - Maestre Aemon, Juego de Tronos

> "El hombre que dicta la condena debe blandir la espada." - Eddard Stark

> "El poder reside donde los hombres creen que reside. Es un truco, una sombra en la pared. Y un hombre muy pequeño puede proyectar una sombra muy grande." - Lord Varys

In [44]:
corpus = [
    "Cuando se juega al Juego de Tronos, solo se puede ganar o morir.",
    "Por qué será que en cuanto un hombre construye un muro, su vecino inmediatamente quiere saber qué hay del otro lado.",
    "¿Qué es el honor, comparado con el amor de una mujer? ¿Qué es el deber, comparado con el calor de un hijo recién nacido entre los brazos, o el recuerdo de la sonrisa de un hermano? Aire y palabras. Aire y palabras. Solo somos humanos, y los dioses nos hicieron para el amor. Es nuestra mayor gloria y nuestra peor tragedia.",
    "El hombre que dicta la condena debe blandir la espada.",
    "El poder reside donde los hombres creen que reside. Es un truco, una sombra en la pared. Y un hombre muy pequeño puede proyectar una sombra muy grande."
]

In [62]:
# Limpieza ddel texto: puntación, minúscula y accentos, stopwords

chars = string.punctuation + '“”¡¿'
re_pun = re.compile('[%s]' % re.escape(chars)) 

for i in range(len(corpus)):
    corpus[i] = re_pun.sub('', corpus[i])
    corpus[i] = corpus[i].lower()
    corpus[i] = unicodedata.normalize('NFD', corpus[i]).encode('ascii', 'ignore').decode("utf-8")
    palabras = corpus[i].split(' ')
    palabras_limpias = [p for p in palabras if p not in stop_words]
    corpus[i] = ' '.join(palabras_limpias)
print(palabras_limpias)
print(corpus)


['poder', 'reside', 'hombres', 'creen', 'reside', 'truco', 'sombra', 'pared', 'hombre', 'pequeno', 'puede', 'proyectar', 'sombra', 'grande']
['juega juego tronos solo puede ganar morir', 'sera cuanto hombre construye muro vecino inmediatamente quiere saber lado', 'honor comparado amor mujer deber comparado calor hijo recien nacido brazos recuerdo sonrisa hermano aire palabras aire palabras solo humanos dioses hicieron amor mayor gloria peor tragedia', 'hombre dicta condena debe blandir espada', 'poder reside hombres creen reside truco sombra pared hombre pequeno puede proyectar sombra grande']


In [70]:
# Create the matrix of word frequencies
count_vectorizer = CountVectorizer()
matrix = count_vectorizer.fit_transform(corpus)

# Get the list of words (column names)
words = count_vectorizer.get_feature_names_out()

# Print the matrix and the list of words
print(matrix.toarray())
print(words)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0
  0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1]
 [2 2 0 1 1 2 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 1 2 0
  1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 1 1 1 1 0 0 0 2 0 0 0 2 0 0 0 1 0]]
['aire' 'amor' 'blandir' 'brazos' 'calor' 'comparado' 'condena'
 'construye' 'creen' 'cuanto' 'debe' 'deber' 'dicta' 'dioses' 'espada'
 'ganar' 'gloria' 'grande' 'hermano' 'hicieron' 'hijo' 'hombre' 'hombres'
 'honor' 'humanos' 'inmediatamente' 'juega' 'juego' 'lado' 'mayor' 'morir'
 'mujer' 'muro' 'nacido' 'palabras' 'pared' 'peor' 'pequeno' 'poder'
 'proyectar' 'puede' 'quiere' 'recien' 'recuerdo' 'reside' 'saber' 'sera'
 'solo'

In [69]:
# Create a DataFrame from the matrix
df = pd.DataFrame(matrix.toarray(), columns=words)
print(df)

TypeError: 'method' object is not iterable